# Generated by Django 4.2.1 on 2023-05-23 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destinations_user_alter_destinations_budget_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='user',
        ),
    ]
